/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package villagedatamanager;

/**
 *
 * @author AdminIGS
 */
public class FormTambahRumah extends javax.swing.JFrame {

    /**
     * Creates new form FormTambahRumah
     */
    
    private int norumah, notelp, jmlhuni;
    private String namapemilik, alamat;
    private ControlRumah ctrlrumah;
    
    public FormTambahRumah(ControlRumah ctrlrumahpass) {
        initComponents();
        this.ctrlrumah = ctrlrumahpass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tambahbtn = new javax.swing.JButton();
        kembalibtn = new javax.swing.JButton();
        norumahtxt = new javax.swing.JTextField();
        namapemiliktxt = new javax.swing.JTextField();
        alamattxt = new javax.swing.JTextField();
        notelptxt = new javax.swing.JTextField();
        jmlhunitxt = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Form Tambah Rumah");

        jLabel2.setText("Nomor Rumah");

        jLabel3.setText("Nama Pemilik");

        jLabel4.setText("Alamat");

        jLabel5.setText("Nomor Telepon");

        jLabel6.setText("Jumlah penghuni");

        tambahbtn.setText("Tambah");
        tambahbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahbtnMouseClicked(evt);
            }
        });

        kembalibtn.setText("Kembali");
        kembalibtn.setToolTipText("");
        kembalibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembalibtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahbtn)
                        .addGap(76, 76, 76)
                        .addComponent(kembalibtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(norumahtxt)
                            .addComponent(namapemiliktxt)
                            .addComponent(alamattxt)
                            .addComponent(notelptxt)
                            .addComponent(jmlhunitxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(norumahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namapemiliktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(notelptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jmlhunitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahbtn)
                    .addComponent(kembalibtn))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahbtnMouseClicked
        // TODO add your handling code here:
        this.namapemilik = namapemiliktxt.getText();
        this.norumah = Integer.parseInt(norumahtxt.getText());
        this.notelp = Integer.parseInt(notelptxt.getText());
        this.alamat = alamattxt.getText();
        this.jmlhuni = Integer.parseInt(jmlhunitxt.getText());
        this.ctrlrumah.tambahRumah(this.norumah, this.notelp, this.alamat, this.namapemilik, this.jmlhuni);
        System.out.print(this.norumah);
        namapemiliktxt.setText("");
        norumahtxt.setText("");
        notelptxt.setText("");
        alamattxt.setText("");
        jmlhunitxt.setText("");
    }//GEN-LAST:event_tambahbtnMouseClicked

    private void kembalibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembalibtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalibtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamattxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JTextField jmlhunitxt;
    private javax.swing.JButton kembalibtn;
    private javax.swing.JTextField namapemiliktxt;
    private javax.swing.JTextField norumahtxt;
    private javax.swing.JTextField notelptxt;
    private javax.swing.JButton tambahbtn;
    // End of variables declaration//GEN-END:variables
}
